<center><h1 style="font-size: 30px;"><b>IBM Data Analyst Capstone Project - Data Preparation</b></h1></center>

<center><h1 style="font-size: 18px;"><b>This notebook outlines the data transformation methodology used to prepare the final dataset for dashboard visualization.</b></h1></center>

In [1]:
# Import Pandas
import pandas as pd
print('Pandas imported successfully')

Pandas imported successfully

In [23]:
# Load csv file into the Pandas Dataframe
path = r"C:\Users\marko\Documents\Notes\IBM Data Analysis\9. IBM Data Analyst Capstone Project\(Module 5) Building A Dashboard\Project Data\survey_data_updated.csv"
df = pd.read_csv(path)
print('Data loaded successfully')

Data loaded successfully

In [24]:
# Let's view the columns that we need to create the dashboard's data
dashboard_df = df[['LanguageHaveWorkedWith','DatabaseHaveWorkedWith','PlatformHaveWorkedWith','WebframeHaveWorkedWith','LanguageWantToWorkWith','DatabaseWantToWorkWith','PlatformWantToWorkWith','WebframeWantToWorkWith','Age','Country','EdLevel']]

In [4]:
# View the first rows of the dataset
dashboard_df.head()

,LanguageHaveWorkedWith,DatabaseHaveWorkedWith,PlatformHaveWorkedWith,WebframeHaveWorkedWith,LanguageWantToWorkWith,DatabaseWantToWorkWith,PlatformWantToWorkWith,WebframeWantToWorkWith,Age,Country,EdLevel
0,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Express;Htmx;Node.js;React;Remix,35-44 years old,United Kingdom of Great Britain and Northern I...,"Bachelor's degree (B.A., B.S., B.Eng., etc.)"
1,C#,Firebase Realtime Database,Google Cloud,ASP.NET CORE,C#,Firebase Realtime Database,Google Cloud,ASP.NET CORE,45-54 years old,United Kingdom of Great Britain and Northern I...,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)"
2,HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Digital Ocean;Fireba...,Express;Next.js;Node.js;React,HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Digital Ocean;Fireba...,Express;Next.js;Node.js;React,35-44 years old,Serbia,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)"
3,JavaScript;Python;Ruby,Elasticsearch;MongoDB;PostgreSQL;SQLite,Amazon Web Services (AWS);Google Cloud,Node.js;React;Ruby on Rails,C#;Crystal;Java;JavaScript;Python;Ruby,Elasticsearch;MongoDB;PostgreSQL;SQLite,Google Cloud,Django;Node.js;React;Ruby on Rails,35-44 years old,United States of America,"Bachelor's degree (B.A., B.S., B.Eng., etc.)"
4,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Power...,Microsoft Access;Microsoft SQL Server;PostgreS...,Cloudflare,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React,C#;HTML/CSS;JavaScript;PowerShell;Rust;SQL;Typ...,Microsoft SQL Server;PostgreSQL;SQLite,Cloudflare,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React,45-54 years old,Poland,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)"

In [5]:
# First we will check for missing and duplicate values in each column
print('Number of null values in each column:')
print(dashboard_df.isnull().sum())
print('Number of duplicates in the dashboard_df:', dashboard_df.duplicated().sum())

Number of null values in each column:
LanguageHaveWorkedWith    0
DatabaseHaveWorkedWith    0
PlatformHaveWorkedWith    0
WebframeHaveWorkedWith    0
LanguageWantToWorkWith    0
DatabaseWantToWorkWith    0
PlatformWantToWorkWith    0
WebframeWantToWorkWith    0
Age                       0
Country                   0
EdLevel                   0
dtype: int64
Number of duplicates in the dashboard_df: 3

In [6]:
# We have 3 duplicate rows that we need to drop
dashboard_df = dashboard_df.drop_duplicates()
# Check after duplicates removal
print('Number of duplicates in the dashboard_df after duplicates removal:', dashboard_df.duplicated().sum())

Number of duplicates in the dashboard_df after duplicates removal: 0

#### We will now create the data for all the count visualization charts.

## Methodology:

The stack overflow survey provides the option to participants to select multiple Languages, Databases, Platforms, and Webframes that they have, or want to work with.

To be able to count these selections, we will need to explode "LanguageHaveWorkedWith", "DatabaseHaveWorkedWith", "PlatformHaveWorkedWith", "WebframeHaveWorkedWith", "LanguageWantToWorkWith", "DatabaseWantToWorkWith", "PlatformWantToWorkWith", "WebframeWantToWorkWith" into rows.

Here we are trying to count the frequency of each technology independently. We must not explode them in the same dataframe. Instead, we will create separate "mini-dataframes" for each category. This will keep row counts manageable and the data clean.

Otherwise, If a respondent has 5 languages, 5 databases, 5 platforms, and 5 webframes, that one person will turn into $5 \times 5 \times 5 \times 5 = 625$ rows. This will affect running time exponentially.

The Big O notation for the number of rows generated would be: $$O(N \cdot M^K)$$

Where:

$N$ = The original number of rows in the dataframe,

$M$ = The average number of items in each list,

$K$ = The number of columns that are being exploded.

### Step 1: Explode into rows

In [7]:
# LanguageHaveWorkedWith
languages_have = dashboard_df['LanguageHaveWorkedWith'].copy()
languages_have = languages_have.str.split(';')
languages_have = languages_have.explode('LanguageHaveWorkedWith')

In [8]:
# DatabaseHaveWorkedWith
database_have = dashboard_df['DatabaseHaveWorkedWith'].copy()
database_have = database_have.str.split(';')
database_have = database_have.explode('DatabaseHaveWorkedWith')

In [9]:
# PlatformHaveWorkedWith
platform_have = dashboard_df['PlatformHaveWorkedWith'].copy()
platform_have = platform_have.str.split(';')
platform_have = platform_have.explode('PlatformHaveWorkedWith')

In [10]:
# WebframeHaveWorkedWith
webframe_have = dashboard_df['WebframeHaveWorkedWith'].copy()
webframe_have = webframe_have.str.split(';')
webframe_have = webframe_have.explode('WebframeHaveWorkedWith')

In [11]:
# LanguageWantToWorkWith
language_want = dashboard_df['LanguageWantToWorkWith'].copy()
language_want = language_want.str.split(';')
language_want = language_want.explode('LanguageWantToWorkWith')

In [12]:
# DatabaseWantToWorkWith
database_want = dashboard_df['DatabaseWantToWorkWith'].copy()
database_want = database_want.str.split(';')
database_want = database_want.explode('DatabaseWantToWorkWith')

In [13]:
# PlatformWantToWorkWith
platform_want = dashboard_df['PlatformWantToWorkWith'].copy()
platform_want = platform_want.str.split(';')
platform_want = platform_want.explode('PlatformWantToWorkWith')

In [14]:
# WebframeWantToWorkWith
webframe_want = dashboard_df['WebframeWantToWorkWith'].copy()
webframe_want = webframe_want.str.split(';')
webframe_want = webframe_want.explode('WebframeWantToWorkWith')

### Step 2: Create mini dataframes

In [15]:
languages_have_df = pd.DataFrame(languages_have)

In [16]:
database_have_df = pd.DataFrame(database_have)

In [17]:
platform_have_df = pd.DataFrame(platform_have)

In [18]:
webframe_have_df = pd.DataFrame(webframe_have)

In [19]:
language_want_df = pd.DataFrame(language_want)

In [20]:
database_want_df = pd.DataFrame(database_want)

In [21]:
platform_want_df = pd.DataFrame(platform_want)

In [22]:
webframe_want_df = pd.DataFrame(webframe_want)

### Step 3: Save and export the csv files

In [23]:
languages_have_df.to_csv(r"C:\Users\marko\Documents\Database\IBM_Capstone_Project_Data\languages_have_df.csv")

In [24]:
database_have_df.to_csv(r"C:\Users\marko\Documents\Database\IBM_Capstone_Project_Data\database_have_df.csv")

In [25]:
platform_have_df.to_csv(r"C:\Users\marko\Documents\Database\IBM_Capstone_Project_Data\platform_have_df.csv")

In [26]:
webframe_have_df.to_csv(r"C:\Users\marko\Documents\Database\IBM_Capstone_Project_Data\webframe_have_df.csv")

In [27]:
language_want_df.to_csv(r"C:\Users\marko\Documents\Database\IBM_Capstone_Project_Data\language_want_df.csv")

In [28]:
database_want_df.to_csv(r"C:\Users\marko\Documents\Database\IBM_Capstone_Project_Data\database_want_df.csv")

In [29]:
platform_want_df.to_csv(r"C:\Users\marko\Documents\Database\IBM_Capstone_Project_Data\platform_want_df.csv")

In [30]:
webframe_want_df.to_csv(r"C:\Users\marko\Documents\Database\IBM_Capstone_Project_Data\webframe_want_df.csv")

#### We will now create the data needed for the rest of the visualization charts.

In [61]:
age_edlevel_country_df = dashboard_df[['Age','Country','EdLevel']].copy()
age_edlevel_country_df

,Age,Country,EdLevel
0,35-44 years old,United Kingdom of Great Britain and Northern I...,"Bachelor's degree (B.A., B.S., B.Eng., etc.)"
1,45-54 years old,United Kingdom of Great Britain and Northern I...,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)"
2,35-44 years old,Serbia,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)"
3,35-44 years old,United States of America,"Bachelor's degree (B.A., B.S., B.Eng., etc.)"
4,45-54 years old,Poland,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)"
...,...,...,...
18840,25-34 years old,Singapore,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)"
18841,18-24 years old,Romania,"Bachelor's degree (B.A., B.S., B.Eng., etc.)"
18842,25-34 years old,Benin,Some college/university study without earning ...
18843,25-34 years old,France,"Bachelor's degree (B.A., B.S., B.Eng., etc.)"
18844,45-54 years old,Belgium,"Bachelor's degree (B.A., B.S., B.Eng., etc.)"

In [62]:
print('Null values in age_edlevel_country_df:')
print(age_edlevel_country_df.isnull().sum())

Null values in age_edlevel_country_df:
Age        0
Country    0
EdLevel    0
dtype: int64

## Methodology:

For practical and dashboard aesthetic reasons, we will trim down the value labels of Age, EdLevel and Country.

E.g. "35-44 years old" --> "35-44", "Bachelor's degree (B.A., B.S., B.Eng., etc.)" --> "Bachelor" and "United States of America" --> "USA".

### Step 1: Create maps or replace value tags

In [63]:
age_edlevel_country_df['Age'].unique()

array(['35-44 years old', '45-54 years old', '25-34 years old',
       '55-64 years old', '18-24 years old', 'Under 18 years old',
       '65 years or older', 'Prefer not to say'], dtype=object)

In [64]:
age_map = {
    '35-44 years old' : '35-44' ,
    '45-54 years old' : '45-54' ,
    '25-34 years old' : '25-34' ,
    '55-64 years old' : '55-64' ,
    '18-24 years old' : '18-24' ,
    'Under 18 years old' : '<18' ,
    '65 years or older' : '>=65' ,
    'Prefer not to say' : 'Prefer not to say'
}

In [65]:
age_edlevel_country_df['EdLevel'].unique()

array(["Bachelor's degree (B.A., B.S., B.Eng., etc.)",
       "Master's degree (M.A., M.S., M.Eng., MBA, etc.)",
       'Professional degree (JD, MD, Ph.D, Ed.D, etc.)',
       'Some college/university study without earning a degree',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Associate degree (A.A., A.S., etc.)', 'Something else',
       'Primary/elementary school'], dtype=object)

In [66]:
edlevel_map = {
    "Bachelor's degree (B.A., B.S., B.Eng., etc.)" : 'Bachelor' ,
    "Master's degree (M.A., M.S., M.Eng., MBA, etc.)" : 'Master' ,
    'Professional degree (JD, MD, Ph.D, Ed.D, etc.)' : 'Professional degree' ,
    'Some college/university study without earning a degree' : 'College/University Student' ,
    'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)' : 'Secondary school' ,
    'Associate degree (A.A., A.S., etc.)' : 'Associate degree' ,
    'Something else' : 'Something else' ,
    'Primary/elementary school' : 'Primary/Elementary School' ,
}

In [67]:
age_edlevel_country_df['Country'].unique()

array(['United Kingdom of Great Britain and Northern Ireland', 'Serbia',
       'United States of America', 'Poland', 'Germany', 'Ireland',
       'Italy', 'Philippines', 'Brazil', 'Austria', 'France', 'Romania',
       'Switzerland', 'Sweden', 'Republic of North Macedonia', 'Greece',
       'United Republic of Tanzania', 'Japan', 'India', 'Argentina',
       'Pakistan', 'Croatia', 'Turkey', 'Portugal', 'Sri Lanka',
       'Hungary', 'Canada', 'Czech Republic', 'Bulgaria', 'Netherlands',
       'Dominican Republic', 'Morocco', 'Russian Federation', 'Tunisia',
       'Bangladesh', 'Ukraine', 'Viet Nam', 'Belgium', 'Spain',
       'South Africa', 'Chile', 'Ghana', 'Israel', 'Bolivia',
       'Luxembourg', 'Georgia', 'Saudi Arabia', 'Algeria', 'Lithuania',
       'Kazakhstan', 'Jordan', 'Venezuela, Bolivarian Republic of...',
       'Denmark', 'Nicaragua', 'Thailand', 'Indonesia', 'Mexico',
       'Slovakia', 'El Salvador', 'Latvia', 'Peru', 'Malaysia', 'Finland',
       'Zimbabwe', 'Malta', 'Uruguay', 'Nigeria', 'Colombia', 'Egypt',
       'Albania', 'Afghanistan', 'Slovenia', 'Palestine', 'Ecuador',
       'Paraguay', 'Ethiopia', 'New Zealand', 'Guatemala',
       'Bosnia and Herzegovina', 'Norway', 'Costa Rica', 'Australia',
       'Kenya', 'Armenia', 'Estonia', 'Iceland', 'Honduras',
       'Hong Kong (S.A.R.)', 'South Korea', 'United Arab Emirates',
       'China', 'Mongolia', 'Singapore', 'Cambodia',
       'Iran, Islamic Republic of...', 'Nepal', 'Uzbekistan', 'Taiwan',
       'Montenegro', 'Lebanon', 'Benin',
       'Democratic Republic of the Congo', 'Belarus', 'Republic of Korea',
       'Cyprus', 'Tajikistan', 'Isle of Man', 'Rwanda', 'Sierra Leone',
       'Panama', 'Cuba', 'Kyrgyzstan', 'Syrian Arab Republic', 'Zambia',
       'Togo', 'Oman', 'Uganda', 'Nomadic', 'Andorra', 'Turkmenistan',
       'Qatar', 'Mauritius', 'Namibia', 'Kosovo', 'Angola',
       "Côte d'Ivoire", 'Malawi', 'Republic of Moldova', 'Iraq',
       'Madagascar', 'Sudan', 'Cameroon', 'Azerbaijan',
       'Central African Republic', 'Myanmar', 'Somalia', 'Suriname',
       'Belize', 'Kuwait', 'Congo, Republic of the...', 'Burkina Faso',
       'Bahrain', 'Yemen', 'Niger', 'Jamaica', 'Mauritania', 'Fiji',
       'Mozambique', 'Antigua and Barbuda', 'Senegal',
       'Trinidad and Tobago', 'Samoa', 'Bhutan', 'Brunei Darussalam',
       'Burundi', 'Guyana', 'Maldives', 'Monaco', 'Mali', 'Cape Verde',
       'Barbados'], dtype=object)

### Step 2: Replace value labels

In [68]:
age_edlevel_country_df['Age'] = age_edlevel_country_df['Age'].map(age_map)

In [69]:
age_edlevel_country_df['EdLevel'] = age_edlevel_country_df['EdLevel'].map(edlevel_map)

In [70]:
age_edlevel_country_df['Country'] = age_edlevel_country_df['Country'].replace('United Kingdom of Great Britain and Northern Ireland','UK')
age_edlevel_country_df['Country'] = age_edlevel_country_df['Country'].replace('United States of America','USA')

### Step 3: View the data

In [71]:
# View the rusult of the changes we made
print('Null values in age_edlevel_country_df:')
print(age_edlevel_country_df.isnull().sum())

Null values in age_edlevel_country_df:
Age        0
Country    0
EdLevel    0
dtype: int64

### Step 4: Save and export the csv file

In [73]:
age_edlevel_country_df.to_csv(r"C:\Users\marko\Documents\Database\IBM_Capstone_Project_Data\age_edlevel_country_df.csv")